In [3]:
!pip install torch torchvision torchaudio
import torch as tc


In [4]:
x = tc.arange(12, dtype=tc.float32).reshape(3, 4)
x

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [5]:
# numel() - returns the total number of elements in the tensor
x.numel()  # 12 elements

12

In [6]:
#  shape - returns the shape of the tensor
x.shape  # torch.Size([3, 4])

torch.Size([3, 4])

In [7]:
#  reshape - changes the shape of the tensor
x_reshaped = x.reshape(4, 3)
x_reshaped

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])

In [8]:
# zeros - creates a tensor filled with zeros
zeros_tensor = tc.zeros((2, 5, 3) )
zeros_tensor

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])

In [9]:
#  ones - creates a tensor filled with ones
ones_tensor = tc.ones((2, 5) )
ones_tensor

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [12]:
#  randn - creates a tensor with random numbers from a normal distribution
randn_tensor = tc.randn((3, 4), dtype=tc.float32)
randn_tensor

tensor([[-0.7127, -1.0388,  0.3956,  0.9264],
        [ 0.0925,  0.4710, -1.4262, -0.1284],
        [-0.2115,  1.2985,  0.4335,  1.1315]])

In [14]:
X = tc.arange(20).reshape(4, 5)

In [17]:
#  indexing and slicing 
X[-1], X[1:3]

(tensor([15, 16, 17, 18, 19]),
 tensor([[ 5,  6,  7,  8,  9],
         [10, 11, 12, 13, 14]]))

In [18]:
X[1,3] = 999
X

tensor([[  0,   1,   2,   3,   4],
        [  5,   6,   7, 999,   9],
        [ 10,  11,  12,  13,  14],
        [ 15,  16,  17,  18,  19]])