In [1]:
import torch as tc
X= tc.arange(20).reshape(4,5)
X

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])

In [2]:
# exp: it returns a new tensor with the exponential of the elements of the input tensor
exp_X = tc.exp(X)
exp_X

tensor([[1.0000e+00, 2.7183e+00, 7.3891e+00, 2.0086e+01, 5.4598e+01],
        [1.4841e+02, 4.0343e+02, 1.0966e+03, 2.9810e+03, 8.1031e+03],
        [2.2026e+04, 5.9874e+04, 1.6275e+05, 4.4241e+05, 1.2026e+06],
        [3.2690e+06, 8.8861e+06, 2.4155e+07, 6.5660e+07, 1.7848e+08]])

In [3]:
# cat using dim =0 (vertically) and dim=1 (horizontally)
cat_dim0 = tc.cat([X, exp_X], dim=0)
cat_dim1 = tc.cat([X, exp_X], dim=1)
cat_dim0, cat_dim1

(tensor([[0.0000e+00, 1.0000e+00, 2.0000e+00, 3.0000e+00, 4.0000e+00],
         [5.0000e+00, 6.0000e+00, 7.0000e+00, 8.0000e+00, 9.0000e+00],
         [1.0000e+01, 1.1000e+01, 1.2000e+01, 1.3000e+01, 1.4000e+01],
         [1.5000e+01, 1.6000e+01, 1.7000e+01, 1.8000e+01, 1.9000e+01],
         [1.0000e+00, 2.7183e+00, 7.3891e+00, 2.0086e+01, 5.4598e+01],
         [1.4841e+02, 4.0343e+02, 1.0966e+03, 2.9810e+03, 8.1031e+03],
         [2.2026e+04, 5.9874e+04, 1.6275e+05, 4.4241e+05, 1.2026e+06],
         [3.2690e+06, 8.8861e+06, 2.4155e+07, 6.5660e+07, 1.7848e+08]]),
 tensor([[0.0000e+00, 1.0000e+00, 2.0000e+00, 3.0000e+00, 4.0000e+00, 1.0000e+00,
          2.7183e+00, 7.3891e+00, 2.0086e+01, 5.4598e+01],
         [5.0000e+00, 6.0000e+00, 7.0000e+00, 8.0000e+00, 9.0000e+00, 1.4841e+02,
          4.0343e+02, 1.0966e+03, 2.9810e+03, 8.1031e+03],
         [1.0000e+01, 1.1000e+01, 1.2000e+01, 1.3000e+01, 1.4000e+01, 2.2026e+04,
          5.9874e+04, 1.6275e+05, 4.4241e+05, 1.2026e+06],
       

In [ ]:
#  ones - creates a tensor filled with ones
ones_tensor = tc.ones((2, 5) )
zeros_tensor = tc.zeros((2, 5) )
ones_tensor == zeros_tensor   # element-wise comparison

tensor([[False, False, False, False, False],
        [False, False, False, False, False]])

In [6]:
ones_tensor.sum()   # sum of all elements in the tensor

tensor(10.)

## Broadcasting

Broadcasting works according to the following two-step procedure:

1. **Expand dimensions**  
   One or both arrays are expanded by copying elements along axes with length **1**, so that after this transformation, both tensors have the **same shape**.

2. **Element-wise operation**  
   Once the shapes match, an **element-wise operation** is performed on the resulting arrays.


In [7]:
a = tc.arange(3).reshape(3, 1)
b = tc.arange(2).reshape(1, 2)
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [8]:
a+b, a*b, a-b

(tensor([[0, 1],
         [1, 2],
         [2, 3]]),
 tensor([[0, 0],
         [0, 1],
         [0, 2]]),
 tensor([[ 0, -1],
         [ 1,  0],
         [ 2,  1]]))

In [11]:
X= 1
Y= 2

In [13]:
Y = X+Y    # new memory is allocated and y kaa adress change ho jata hai
Y

3

In [14]:
# in-place operation
X= 1
Y= 2
Y += X   # no new memory is allocated, y kaa adress change nahi hota

In [15]:
# slice assignments
Z = tc.zeros((3, 3))
Z[:, 1] = 5
Z

tensor([[0., 5., 0.],
        [0., 5., 0.],
        [0., 5., 0.]])

## Conversion to Other Python Objects


In [19]:
import torch

X = torch.tensor(5)
a = X.numpy()
b = torch.from_numpy(a)
type(a), type(b)

(numpy.ndarray, torch.Tensor)

In [20]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)


(tensor([3.5000]), 3.5, 3.5, 3)